name: Npact
favicon: null
layout_spectrum: 0.36142
typography_spectrum: 0.45023
title: 'Npact | Energy Efficiency Made Easy'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-55313957-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#005aff'
    - '#29b281'
    - '#8cc63e'
    - '#4281f6'
  brandStrength: 0.125
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
